// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5fPQJxM467nBhY__XpYK77Ut1cdbB63E',
    appId: '1:963279705517:web:19446d5fbf2e19c434bd24',
    messagingSenderId: '963279705517',
    projectId: 'minimal-social-app-289f2',
    authDomain: 'minimal-social-app-289f2.firebaseapp.com',
    storageBucket: 'minimal-social-app-289f2.appspot.com',
    measurementId: 'G-SGC7NFMFWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWcS5KFHA2xfwWncgUotFj3XwL35CubGE',
    appId: '1:963279705517:android:e555b36baef6347134bd24',
    messagingSenderId: '963279705517',
    projectId: 'minimal-social-app-289f2',
    storageBucket: 'minimal-social-app-289f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCccfK8P4LsxOsoop7DUkbF2NYY0h9tG6w',
    appId: '1:963279705517:ios:a357e445e27e23bf34bd24',
    messagingSenderId: '963279705517',
    projectId: 'minimal-social-app-289f2',
    storageBucket: 'minimal-social-app-289f2.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCccfK8P4LsxOsoop7DUkbF2NYY0h9tG6w',
    appId: '1:963279705517:ios:a357e445e27e23bf34bd24',
    messagingSenderId: '963279705517',
    projectId: 'minimal-social-app-289f2',
    storageBucket: 'minimal-social-app-289f2.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5fPQJxM467nBhY__XpYK77Ut1cdbB63E',
    appId: '1:963279705517:web:971e4cab9448de9c34bd24',
    messagingSenderId: '963279705517',
    projectId: 'minimal-social-app-289f2',
    authDomain: 'minimal-social-app-289f2.firebaseapp.com',
    storageBucket: 'minimal-social-app-289f2.appspot.com',
    measurementId: 'G-K6VSGNTRDD',
  );
}
